<a href="https://colab.research.google.com/github/Suvigya-bisht/5th-sem-Mini-project/blob/main/mpsem5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Mounting drive.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Importing necessary liberaries.

In [ ]:
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import numpy as np # linear algebra

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
path = "/content/drive/MyDrive/Hindi_bible.csv"

Reading the dataframe from bible.csv

In [ ]:
df= pd.read_csv(path)

Displaying "n" number of lines.

In [ ]:
df.head(10)

Unnamed: 0  Book  ...  Verse id                                               Text
0           0     0  ...     0-0-0   आदि में परमेश्वर ने आकाश और पृथ्वी की सृष्टि की।
1           1     0  ...     0-0-1  और पृथ्वी बेडौल और सुनसान पड़ी थी; और गहरे जल ...
2           2     0  ...     0-0-2  तब परमेश्वर ने कहा, उजियाला हो: तो उजियाला हो ...
3           3     0  ...     0-0-3  और परमेश्वर ने उजियाले को देखा कि अच्छा है; और...
4           4     0  ...     0-0-4  और परमेश्वर ने उजियाले को दिन और अन्धियारे को ...
5           5     0  ...     0-0-5  फिर परमेश्वर ने कहा, जल के बीच एक ऐसा अन्तर हो...
6           6     0  ...     0-0-6  तब परमेश्वर ने एक अन्तर करके उसके नीचे के जल औ...
7           7     0  ...     0-0-7  और परमेश्वर ने उस अन्तर को आकाश कहा। तथा सांझ ...
8           8     0  ...     0-0-8  फिर परमेश्वर ने कहा, आकाश के नीचे का जल एक स्थ...
9           9     0  ...     0-0-9  और परमेश्वर ने सूखी भूमि को पृथ्वी कहा; तथा जो...

[10 rows x 6 columns]

Install pytorch for deep learning. 
Necessity for iNLTK

In [ ]:
!pip3 install torch==1.2.0+cu92 torchvision==0.4.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 663.1 MB 1.7 kB/s 
     |████████████████████████████████| 8.8 MB 37.1 MB/s 
  Attempting uninstall: torch
    Found existing installation: torch 1.10.0+cu111
    Uninstalling torch-1.10.0+cu111:
      Successfully uninstalled torch-1.10.0+cu111
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.11.1+cu111
    Uninstalling torchvision-0.11.1+cu111:
      Successfully uninstalled torchvision-0.11.1+cu111
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchtext 0.11.0 requires torch==1.10.0, but you have torch 1.2.0+cu92 which is incompatible.
torchaudio 0.10.0+cu111 requires torch==1.10.0, but you have torch 1.2.0+cu92 which is incompatible.


Installing iNLTK toolkit.

In [ ]:
!pip install inltk

     |████████████████████████████████| 1.1 MB 5.2 MB/s 
     |████████████████████████████████| 78 kB 3.5 MB/s 
     |████████████████████████████████| 233 kB 44.5 MB/s 
     |████████████████████████████████| 1.2 MB 40.6 MB/s 
     |████████████████████████████████| 192 kB 40.8 MB/s 
     |████████████████████████████████| 160 kB 47.0 MB/s 
     |████████████████████████████████| 271 kB 45.6 MB/s 
  Created wheel for typing: filename=typing-3.7.4.3-py3-none-any.whl size=26324 sha256=2e36470b9b8ee7833d04c8c9c5afd7d4e0b8f5e8a0964fd1d683748bd165f0a7
  Stored in directory: /root/.cache/pip/wheels/35/f3/15/01aa6571f0a72ee6ae7b827c1491c37a1f72d686fd22b43b0e
Successfully built typing
  Attempting uninstall: fastai
    Found existing installation: fastai 1.0.61
    Uninstalling fastai-1.0.61:
      Successfully uninstalled fastai-1.0.61


In [ ]:
from inltk.inltk import setup

Setting up Hindi as language with "hi" as code.

In [ ]:
setup('hi')

RuntimeError: ignored

Done!


Displaying 'n' number of lines.

In [ ]:
df.head(10)

Unnamed: 0  Book  ...  Verse id                                               Text
0           0     0  ...     0-0-0   आदि में परमेश्वर ने आकाश और पृथ्वी की सृष्टि की।
1           1     0  ...     0-0-1  और पृथ्वी बेडौल और सुनसान पड़ी थी; और गहरे जल ...
2           2     0  ...     0-0-2  तब परमेश्वर ने कहा, उजियाला हो: तो उजियाला हो ...
3           3     0  ...     0-0-3  और परमेश्वर ने उजियाले को देखा कि अच्छा है; और...
4           4     0  ...     0-0-4  और परमेश्वर ने उजियाले को दिन और अन्धियारे को ...
5           5     0  ...     0-0-5  फिर परमेश्वर ने कहा, जल के बीच एक ऐसा अन्तर हो...
6           6     0  ...     0-0-6  तब परमेश्वर ने एक अन्तर करके उसके नीचे के जल औ...
7           7     0  ...     0-0-7  और परमेश्वर ने उस अन्तर को आकाश कहा। तथा सांझ ...
8           8     0  ...     0-0-8  फिर परमेश्वर ने कहा, आकाश के नीचे का जल एक स्थ...
9           9     0  ...     0-0-9  और परमेश्वर ने सूखी भूमि को पृथ्वी कहा; तथा जो...

[10 rows x 6 columns]

Selecting a string to work on.

In [ ]:
text = df.Text[0]

String Tokenization

In [ ]:
from inltk.inltk import tokenize
tokenize(text,"hi")

['▁आदि',
 '▁में',
 '▁परमेश्वर',
 '▁ने',
 '▁आकाश',
 '▁और',
 '▁पृथ्वी',
 '▁की',
 '▁सृष्टि',
 '▁की',
 '।']

Generation of "n" number of similar sentences. Here degree of augmentation (degree_of_aug) is roughly the percentage of sentence you want to augment, with a default value of 0.1

In [ ]:
from inltk.inltk import get_similar_sentences
get_similar_sentences(text, 10, 'hi')

['आदिमें परमेश्वर ने आकाश और पृथ्वी की सृष्टि की।',
 'इत्यादी में परमेश्वर ने आकाश और पृथ्वी की सृष्टि की।',
 'आदि तक परमेश्वर ने आकाश और पृथ्वी की सृष्टि की।',
 'आदि में परमेश्वर ने आकाश और धरातल की सृष्टि की।',
 'आदिमे परमेश्वर ने आकाश और पृथ्वी की सृष्टि की।',
 'आदि में परमेश्वर जिसने आकाश और पृथ्वी की सृष्टि की।',
 'आदि में परमेश्वर जिसने आकाश और पृथ्वी की सृष्टि की।',
 'आदि हेतु परमेश्वर ने आकाश और पृथ्वी की सृष्टि की।',
 'आदि में राजर्षि ने आकाश और पृथ्वी की सृष्टि की।',
 'आदि में वैवस्वत ने आकाश और पृथ्वी की सृष्टि की।']

Prediction of next "n" words.


In [ ]:
from inltk.inltk import predict_next_words
predict_next_words(text , 20, 'hi') 

'आदि में परमेश्वर ने आकाश और पृथ्वी की सृष्टि की। जीव और जगत् का पोषण है। ब्रह्म ही सभी प्राणियों में एक का रूप है। इसे तीन भागों'

Embedded vectors: here 400 is returned for "hi" as code for hindi

In [ ]:
from inltk.inltk import get_embedding_vectors

vectors = get_embedding_vectors(text, 'hi')
vectors[0].shape

(400,)

Getting embedding vectors value in array form for each word of the line(text).

In [ ]:
get_embedding_vectors(text,'hi')

[array([-0.328562, -0.203395,  0.524923, -0.362378, ...,  0.49079 , -0.077877,  0.2116  , -0.766575], dtype=float32),
 array([-0.091106, -0.041014,  0.135212, -0.359347, ..., -0.833676,  0.377581,  0.561746,  0.391029], dtype=float32),
 array([ 0.509354, -0.199595,  0.326825, -0.768012, ..., -0.130998, -0.431516,  0.387919, -0.293797], dtype=float32),
 array([ 0.093869,  0.118591, -0.120096, -0.369142, ..., -0.412894,  0.355545,  0.459137,  0.51733 ], dtype=float32),
 array([ 0.133121,  0.068303,  0.41899 , -0.363495, ..., -0.0717  ,  0.317622,  1.320187, -0.132463], dtype=float32),
 array([-0.251645, -0.016307, -0.53508 , -0.243515, ...,  1.056107,  0.367395,  0.271106,  0.158422], dtype=float32),
 array([ 0.393039, -0.157434,  0.125727, -0.785013, ..., -0.503091,  0.210558,  0.723028,  0.450264], dtype=float32),
 array([-0.434602,  0.030792, -0.378546, -0.317925, ..., -0.474518,  0.324979,  0.501039,  0.261285], dtype=float32),
 array([ 0.433999,  0.296306, -0.111096, -0.611774, ...,

Length/number of the embedded vector's array

In [ ]:
vectors = get_embedding_vectors(text,'hi')
len(vectors)

11

Calculating sentence similarity between two texts (text and sentence here).

In [ ]:
sentence = df.Text[1]

In [ ]:
from inltk.inltk import get_sentence_similarity
get_sentence_similarity(text, sentence, 'hi')

0.5314226746559143

Displaying 'n' number of lines from the dataframe.

In [ ]:
df.head(10)

Unnamed: 0  Book  ...  Verse id                                               Text
0           0     0  ...     0-0-0   आदि में परमेश्वर ने आकाश और पृथ्वी की सृष्टि की।
1           1     0  ...     0-0-1  और पृथ्वी बेडौल और सुनसान पड़ी थी; और गहरे जल ...
2           2     0  ...     0-0-2  तब परमेश्वर ने कहा, उजियाला हो: तो उजियाला हो ...
3           3     0  ...     0-0-3  और परमेश्वर ने उजियाले को देखा कि अच्छा है; और...
4           4     0  ...     0-0-4  और परमेश्वर ने उजियाले को दिन और अन्धियारे को ...
5           5     0  ...     0-0-5  फिर परमेश्वर ने कहा, जल के बीच एक ऐसा अन्तर हो...
6           6     0  ...     0-0-6  तब परमेश्वर ने एक अन्तर करके उसके नीचे के जल औ...
7           7     0  ...     0-0-7  और परमेश्वर ने उस अन्तर को आकाश कहा। तथा सांझ ...
8           8     0  ...     0-0-8  फिर परमेश्वर ने कहा, आकाश के नीचे का जल एक स्थ...
9           9     0  ...     0-0-9  और परमेश्वर ने सूखी भूमि को पृथ्वी कहा; तथा जो...

[10 rows x 6 columns]

# THANK YOU
# THE END